global:
  environment: dev
backend:
  replicaCount: 1
  image:
    repository: quay.io/subirrastogi/todo-backend
    tag: b291113
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
gateway:
  replicaCount: 1
  image:
    repository: quay.io/subirrastogi/todo-api-gateway
    tag: "0506166"
ui:
  replicaCount: 1
  image:
    repository: quay.io/subirrastogi/todo-ui
    tag: da692fb
route:
  enabled: true
  host: todo-dev.apps.mycluster.example.com
